### ISSUE TITLE
Premium Purchase

### ISSUE THREAD

**Issue by codedbean** [Panl/AICat#13]
Where would I be able to create the ID's at?

let monthlyPremiumId = "monthly premium subscription product id"
let catFoodId = "consumable in-app purchase product id"

**Comment by Panl** [comment]
> Where would I be able to create the ID's at?
> 
> let monthlyPremiumId = "monthly premium subscription product id"
> let catFoodId = "consumable in-app purchase product id"

App connect：developer.apple.com

**Comment by Panl** [comment]
AICat use Apphud to handle in-app purchases, you should also create an Apphud account and enter the ID's in Apphud's console

**Comment by Panl** [comment]
You should enter monthlyPremiumId, catFoodId in the Apphud paywall, you should read Apphud's developer doc
