### ISSUE TITLE
macos 同步显示弹窗

### ISSUE THREAD

**Issue by Kerwin1202** [Panl/AICat#2]
1. 当我点 这个的时候 托盘也会弹出来， 而且这个时候托盘的弹窗一直显示 不会隐藏，除非手动点一次托盘图标
<img width="442" alt="image" src="https://user-images.githubusercontent.com/16319833/230719903-8b0d2845-6a02-4cbe-8a27-ccae6bbf5abf.png">

2.  这个弹窗只有 esc 关闭 不能点关闭按扭（就没按扭）或者背景

<img width="503" alt="image" src="https://user-images.githubusercontent.com/16319833/230719948-2bd04bc0-f068-4ee2-8e57-b68249f99255.png">

**Comment by Panl** [comment]
fixed
